### ISSUE TITLE
Django app serving static files is not working as expected behavior

### ISSUE THREAD

**Issue by gangularamya** [Azure-App-Service/python#12]
I was trying to deploy Django App on App service Linux Python 3.7. 
Serving static files works locally...but not on app services
Here is my GitHub sample on Django app
https://github.com/gangularamya/AzurePythonDjangoWAFL
Any idea how to fix it?

**Comment by JennyLawrance** [comment]
Whitenoise is a good alternative to serve static content from django apps.
http://whitenoise.evans.io/en/stable/

**Comment by shahed-swe** [comment]
is there any way to do this thing without using any third-party like whitenoise?
