### ISSUE TITLE
Missing libmysqlclient.so in Python Image

### ISSUE THREAD

**Issue by qubitron** [Azure-App-Service/python#16]
The libmysqlclient package, which is the recommended one for use with Django isn't available in the Python image:
![image](https://user-images.githubusercontent.com/17804393/49680342-4363bf80-fa48-11e8-898e-521388b91332.png)

Code is available here: https://github.com/nnja/tweeter3/tree/mysql and instructions are in the README.

**Comment by JennyLawrance** [comment]
Ack, taking a look.

**Comment by patricklee2** [comment]
this should be fixed now with the move to oryx
https://github.com/microsoft/Oryx/blob/676883f1de9898c0f1c31b1495a13e358ea69e47/images/runtime/python/install-dependencies.sh#L15
