### ISSUE TITLE
Problem having equals ("=") in environment variables values

### ISSUE THREAD

**Issue by Aorimn** [Azure-App-Service/python#23]
We tried to have equals in the values of environment variables (for a Redis-generated key that is base64-encoded, but that shouldn't matter), but failed to have the proper value in the running app.

We've managed to pinpoint (at least that's from an external, newbie point-of-view) the issue to the [init_container](https://github.com/Azure-App-Service/python/blob/master/3.7.0/init_container.sh#L24) script. The `awk` is performed with the equal sign ("=") as the field separator, breaking any environment value with this character.

A possible idea would be to do something like this instead:
```bash
printenv | awk -F= 'sub("^([^=]+)=", "export "$1"=")'
```

I'm not an `awk` expert so I cannot really explain how it works or if it doesn't have any side effect, I just tested it like so on an Ubuntu:
```bash
$ export FOO=BAR=

$ printenv |grep FOO
FOO=BAR=

$ printenv | awk -F= '{print "export " $1"="$2 }' | grep FOO
export FOO=BAR

$ printenv | awk -F= 'sub("^([^=]+)=", "export "$1"=")'  | grep FOO
export FOO=BAR=
```

**Comment by patricklee2** [comment]
fixed with #36
